BookiernesApp/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.views.generic import RedirectView, ListView

from django.conf import settings
from django.conf.urls.static import static

from BookiernesApp.views import *

app_name = "BookiernesApp"

urlpatterns = [
    path('', login_required(mainView), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),

    #Escritor
    # http://127.0.0.1:8000/writer_published/
    url(r'^writer_published/$', login_required(PublishedBooks.as_view()), name='writer_published_books'),
    # http://127.0.0.1:8000/writer_published/get_book/33
    url(r'^writer_published/get_book/(?P<pk>\d+)/$', login_required(Get_Books.as_view()), name='books'),
    # http://127.0.0.1:8000/writer_published/add_book/
    url(r'^writer_published/add_book/$', login_required(PublishBook.as_view()), name='writer_publish_book'),
    # http://127.0.0.1:8000/writer_published/edit_book/33
    url(r'^writer_published/edit_book/(?P<pk>\d+)/$', login_required(Edit_Book.as_view()), name='writer_modify_a_book'),
    # http://127.0.0.1:8000/writer_published/edit_book/33
    url(r'^writer_message/get_book/(?P<pk>\d+)/$', login_required(Chat_Book.as_view()), name='chat_book'),
    url(r'^writer_message/post_book/(?P<pk>\d+)/send/$', login_required(post_chat), name='send_message'),

    url(r'^writer_published/book_delete/(?P<pk>\d+)$', login_required(deleteBook), name='book_delete'),

    url(r'^writer_notification/(?P<pk>\d+)/$', login_required(writer_notification), name='notification'),

    url(r'^writer_published/serch/$', login_required(SerchBooks.as_view()), name='serch_book'),

    # Editor
    url(r'^editor_book_revision/$', login_required(EditorBookRevision.as_view()), name='editor_book_revision'),


    url(r'^editor_message/get_book/(?P<pk>\d+)/$', login_required(Editor_Chat_Book.as_view()), name='chat_book_editor'),
    url(r'^editor_message/post_book/(?P<pk>\d+)/send/$', login_required(editor_post_chat), name='send_message_editor'),
    url(r'^editor_notification/(?P<pk>\d+)/$', login_required(editor_notification), name='notification_editor'),


    # Main Editor
    #url(r'^maineditor_book_revision/$', login_required(MainEditorBookRevision.as_view()), name='maineditor_book_revision'),


    #url(r'^maineditor_message/get_book/(?P<pk>\d+)/$', login_required(Maineditor_Chat_Book.as_view()), name='chat_book_maineditor'),
    #url(r'^maineditor_message/post_book/(?P<pk>\d+)/send/$', login_required(maineditor_post_chat), name='send_message_maineditor'),
    #url(r'^maineditor_notification/(?P<pk>\d+)/$', login_required(maineditor_notification), name='notification_maineditor'),




    path('', SignUpView.as_view(), name='signup'),
    # writer

    # editor urls
    url(r'^editor_book_revision/$', EditorBookRevision.as_view(), name='editor_book_revision'),
    url(r'^editor_book_revision/book_revision_detail/(?P<pk>\d+)/$',
        EditorBookDetail.as_view(), name='editor_book_detail'),
    url(r'^editor_book_revision/book_revision_detail/(?P<pk>\d+)/accept_or_reject$',
        accept_or_reject, name='editor_accept_or_reject'),

    url(r'^editor_books_to_design/book_design_detail/(?P<pk>\d+)/$',
        EditorBookDesignDetail.as_view(), name='editor_design_detail'),

    path('editor_books_to_design', EditorBooksToDesign.as_view(), name='editor_books_to_design'),
    path('editor_image_petitions', EditorImagePetitions.as_view(), name='editor_image_petitions'),
    path('editor_image_petitions/image_petition_detail/<int:pk>/', EditorImagePetitionDetail.as_view(), name='image_petition_detail'),
    path('editor_image_petitions/new_petiton', EditorImagePetitionsCreate.as_view(), name='editor_image_petition_create'),

    # main editor urls
    # TODO create date_presented attribute to sort books
    url(r'^maineditor__books_presented_in_editorial/$',
        MainEditorBooksPresentedInEditorial.as_view(), name='maineditor_books_presented_editorial'),
    url(r'^maineditor__books_presented_in_editorial/book_presented_detail/(?P<pk>\d+)/$',
        MainEditorBookPresentedDetail.as_view(), name='maineditor_book_presented_detail'),
    url(r'^maineditor__books_presented_in_editorial/book_presented_detail/(?P<pk>\d+)/assign_or_reject$',
        assign_or_reject, name='maineditor_assign_or_reject'),


    # it urls
    url(r'^it_view/$', ItView.as_view(), name='user_list'),
    url(r'^it_view/get_user/(?P<pk>\d+)/$', ItDetailUser.as_view(), name='user_view'),
    url(r'^it_view/active_user/(?P<pk>\d+)/$', active_user, name='active_user'),
    url(r'^it_view/add_user/$', ITCrateUser.as_view(), name='create_user'),
    url(r'^it_view/edit_pass/(?P<pk>\d+)/$', ItPassword.as_view(), name='user_edit_pass'),
    url(r'^it_view/edit_pass_post/$', postEditPass, name='user_edit_pass_post'),
    url(r'^reset/password/$', ViewResetPass.as_view(), name='reset_password_view'),
    url(r'^post/reset/password/$', resetPass, name='reset_password'),


    # Graphic Designer main
    url(r'^main_graphic_designer/petitionview/$', AssignmentListImg.as_view(), name='main_petitionview_list'),
    url(r'^main_graphic_designer/get_petitionview/(?P<pk>\d+)/$', AssignmentDetaliImg.as_view(), name='main_petitionview_view'),

    url(r'^main_graphic_designer/bockmaquetat/$', AssignmentListBockMaquetat.as_view(), name='main_bockmaquetat_list'),
    url(r'^main_graphic_designer/get_bockmaquetat/(?P<pk>\d+)/$', AssignmentDetaliBockMaquetat.as_view(), name='main_bockmaquetat_view'),

    url(r'^main_graphic_designer/post_to_assign_GraphicDesigner/$', asignarGraphicDesigner,name='main_to_assign_graphicdesigner'),

    # Graphic Designer
    url(r'^graphic_designer/petitionview/$', ListImg.as_view(), name='petitionview_list'),
    url(r'^graphic_designer/get_petitionview/(?P<pk>\d+)/$', DetaliImg.as_view(), name='petitionview_view'),
    url(r'^graphic_designer/bockmaquetat/$', ListBockMaquetat.as_view(), name='bockmaquetat_list'),
    url(r'^graphic_designer/get_bockmaquetat/(?P<pk>\d+)/$', DetaliBockMaquetat.as_view(), name='bockmaquetat_view'),

    url(r'^graphic_designer/post_bockmaquetat/uploadbook/(?P<pk>\d+)/$', uploadbook, name='uploadbook_post'),
    url(r'^graphic_designer/post_bockmaquetat/uploadimg/$', uploadimg, name='uploadimg_post'),

    url(r'^graphic_designer/uploadimg/viewimg/(?P<pk>\d+)/$', GalleryImg.as_view(), name='get_uploadimg_view'),
    url(r'^graphic_designer/post_bockmaquetat/deleteimg/(?P<pk>\d+)/$', delete_img, name='get_deleteimg'),

    url(r'^graphic_designer_notification/(?P<pk>\d+)/$', designer_notification, name='notification_graphic_designer'),

    url(r'^graphic_designer_message/get_book/(?P<pk>\d+)/$', Graphic_designer_Chat_Book.as_view(), name='chat_book_graphic_designer'),
    url(r'^graphic_designer_message/post_book/(?P<pk>\d+)/send/$', graphic_designer_post_chat, name='send_message_graphic_designer'),




    #lector
    url(r'^landing_page/$', Landing_page_List.as_view(), name='landing_page'),
    url(r'^landing_page_search/(?P<type>\d+)/(?P<pk>\d+)/$', Landing_page_search.as_view(), name='landing_page_search'),
    url(r'^landing_page_search_from/$', Landing_page_search_from.as_view(), name='landing_page_search_from'),
    url(r'^autocomplete/book_autocomplete/$' , book_autocomplete , name='book_autocomplete'),

    url(r'^get_book/(?P<pk>\d+)/$', AssignmentDetaliImg.as_view(), name='get_book'),
    url(r'^register_readers/$', RegisterReaders.as_view(), name='register_readers'),
    url(r'^dowload_pdf/(?P<pk>\d+)/$', dowload_pdf, name='dowload_pdf'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookiernesSystem/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BookiernesApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookiernesApp/views/it_views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, TemplateView, CreateView, UpdateView, DeleteView, ListView
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib import messages
from django.contrib.messages import constants

from django.urls import  reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.conf import settings

from BookiernesApp.decorators import it_required
from BookiernesApp.forms import FormularioUsuario

from BookiernesApp.models import User, Theme


@method_decorator([login_required, it_required], name='dispatch')
class ItView(ListView):
    template_name = 'html_templates/IT/It_UserList.html'
    model = User
    paginate_by = 10

    def get_queryset(self):
        try:
            return User.objects.exclude(user_type = "subscribed_reader").exclude(username="admin")
        except:
            return 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj_user_count'] = User.objects.exclude(user_type="subscribed_reader").exclude(
            username="admin").count()
        return context


@method_decorator([login_required, it_required], name='dispatch')
class ItDetailUser(TemplateView):
    model = User
    template_name = 'html_templates/IT/It_DadesUser.html'


    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['obj_user_count'] = User.objects.exclude(user_type = "subscribed_reader").exclude(username="admin").count()
            context['obj_user'] = User.objects.get(id=self.kwargs['pk'])
            return context
        except:
            raise Http404("I can't access this page.")

@method_decorator([login_required, it_required], name='dispatch')
class ITCrateUser(SuccessMessageMixin, CreateView):
    model = User
    template_name = 'html_templates/IT/It_CreateUser.html'
    form_class = FormularioUsuario
    success_url = reverse_lazy('BookiernesApp:user_list')

    def get_success_message(self, cleaned_data):
        return "L'usuari %(name)s s'ha creat correctament. " % {'name': self.object.username}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj_user_count'] = User.objects.exclude(user_type="subscribed_reader").exclude(
            username="admin").count()
        context['Theme'] = Theme.objects.all()
        return context

@method_decorator([login_required, it_required], name='dispatch')
class ItPassword(TemplateView):
    template_name = 'html_templates/IT/ItEditPassword.html'

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['obj_user_count'] = User.objects.exclude(user_type="subscribed_reader").exclude(
                username="admin").count()
            context['obj_user'] = User.objects.get(id=self.kwargs['pk'])
            return context
        except:
            raise Http404("No puc accedir a aquesta pàgina.")


@login_required
@it_required
def postEditPass(request):
    if request.method == "POST":

        message = ""
        ok=0
        id = request.POST['pk']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        obj_user = User.objects.get(id=id)

        if pass1 != pass2 or (len(pass1)<8 and len(pass2)<8):
            message = "La contrasenya ha de tenir 8 caràcters i els dos camps han de ser iguals. "
        else:
            message = "A l'usuari %(nom)s se li ha canviat la contrasenya. " % {'nom': obj_user.username}
            ok = 1



        if ok == 1:
            messages.add_message(request, constants.SUCCESS, message)
            obj_user.set_password(pass2)
            obj_user.save()
            return redirect("BookiernesApp:user_list")
        else:
            messages.add_message(request, constants.ERROR, message)
            url = "/it_view/edit_pass/" + str(obj_user.id)
            return redirect(url)

    else:
        raise Http404("No puc accedir a aqueta pàgina.")


@method_decorator([login_required, it_required], name='dispatch')
class ViewResetPass(TemplateView):
    template_name = 'html_templates/IT/It_PeticonCabio.html'

@login_required
@it_required
def resetPass(request):
    return redirect("/")

@login_required
@it_required
def active_user(request, pk):
    try:
        obj_user=User.objects.get(id = pk)
        message= ""
        url="BookiernesApp:user_list"

        if obj_user.is_active == 1:
            obj_user.is_active=0
            message = "L'usuari %(nom)s s'ha desactivat correctament. " % {'nom': obj_user.username}
        else:
            obj_user.is_active = 1
            message = "L'usuari %(nom)s s'ha activat correctament. " % {'nom': obj_user.username}

        obj_user.save()


        messages.add_message(request, constants.SUCCESS, message)

        return redirect(url)

    except:
        raise Http404("No puc accedir a aquesta pàgina")

BookiernesApp/views/maineditor_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic import TemplateView
from django.http import Http404
from django.shortcuts import render , redirect
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin

from datetime import datetime

from BookiernesApp.decorators import mainEditor_required, book_presented
from BookiernesApp.models import *

from BookiernesApp.decorators import mainEditor_required
from BookiernesApp.models import Book, User, Writer, Editor, Notification , Message

@method_decorator([login_required, mainEditor_required], name='dispatch')
class MainEditorBooksPresentedInEditorial(ListView):

    model = Book
    template_name = 'html_templates/MainEditor/MainEditor_PresentedBooks.html'
    #paginate_by = 100  # if pagination is desired


@method_decorator([login_required, mainEditor_required, book_presented], name='dispatch')
class MainEditorBookPresentedDetail(DetailView):

    model = Book
    template_name = 'html_templates/MainEditor/MainEditor_DetailPresentedBook.html'


@login_required
@mainEditor_required
def assign_or_reject(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.POST['action'] == 'assign':
        #Find editors with the same theme as the book
        possible_users = User.objects.all().filter(editor_profile__assigned_theme=book.theme)
        if not possible_users:
            return redirect('BookiernesApp:maineditor_books_presented_editorial')  #TODO test print error message, no users found with this theme
        #Find the least busy worker
        available_user = list(possible_users)[0]
        for user in possible_users:
            if available_user != user and user.editor_profile.get_availability() < available_user.editor_profile.get_availability():
                available_user = user
        #Modify book attributes
        book.assigned_to = available_user.editor_profile
        book.book_status = 'revised'
        book.main_editor_comment = request.POST['maineditor_approved_comment']
    elif request.POST['action'] == 'reject':
        book.book_status = 'rejected'
        book.main_editor_comment = request.POST['maineditor_rejected_comment']
    book.save()
    #Redirect
    return redirect('BookiernesApp:maineditor_books_presented_editorial')

BookiernesApp/views/shared_views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import CreateView

from BookiernesApp.forms import SignUpForm
from BookiernesApp.models import *


@login_required
def mainView(request):
    user = User.objects.get(username=request.user.username)
    if user.user_type == 'writer':
        return redirect('BookiernesApp:writer_published_books')
    elif user.user_type == 'editor':
        return redirect('BookiernesApp:editor_book_revision')
    elif user.user_type == 'main_editor':
        return redirect('BookiernesApp:maineditor_books_presented_editorial')
    elif user.user_type == 'it':
        return redirect('BookiernesApp:user_list')
    elif user.user_type == 'main_graphic_designer':
        return redirect('BookiernesApp:main_petitionview_list')
    elif user.user_type == 'graphic_designer':
        return redirect('BookiernesApp:petitionview_list')
    elif user.user_type == 'subscribed_reader':
        return redirect('BookiernesApp:landing_page')



class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'forms/form.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('BookiernesApp:home')

BookiernesApp/templates/html_templates/IT/ItEditPassword.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookiernes</title>
   <!-- Google Font: Source Sans Pro -->
    <!-- libreria para caja de texto  -->
    <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">

{% endblock %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">

        <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="{% url 'BookiernesApp:user_list' %}">Llistat de treballadors</a></li>
            <li class="breadcrumb-item">Canviar contrasenya</li>

        </ol>


      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
</br>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Canviar la contrasenya a {{obj_user.username}} </h3>
                </div>

                   {% if messages %}

                {% for message in messages %}
                <br>
                <div class="container">
                <div class="row justify-content-md-center">
                <div class="col-md-6">
                  <div class="card card-danger ">
                    <div class="card-header">
                      <h3 class="card-title">Èxit</h3>

                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
                        </button>
                      </div>
                      <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      {{message}}
                    </div>
                    <!-- /.card-body -->
                  </div>
                </div>
              </div>
            </div>
                {% endfor %}

                {% endif %}

                <form action="{% url 'BookiernesApp:user_edit_pass_post' %}"  method="POST"  enctype="multipart/form-data">
                  {% csrf_token %}
 <input type="text" name="pk" class="form-control invisible" id="id"  value="{{obj_user.id}}">
                  <div class="card-body">
                    <div class="form-group">
                      <label >Ingressi la nova contrasenya</label>
 <input type="password" name="pass1" class="form-control" id="pass1" maxlength="140" required="">
                    </div>
                    <div class="form-group">
                      <label >Repeteixi la nova contrasenya</label>
 <input type="password" name="pass2" class="form-control" id="pass2" maxlength="255" required="">
                    </div>



                  </div>

                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Canviar contrasenya</button>
                  </div>
                </form>
              </div>



        </div>
    </section>
    <!-- /.content -->
  </div>
{% endblock %}

BookiernesApp/templates/html_templates/IT/It_PeticonCabio.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Log in</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../static/BookiernesApp/css/all.min.css">
  <!-- iconas fas -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

  <!-- Theme style -->
  <link rel="stylesheet" href="../../static/BookiernesApp/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">

    <div class="text-center">
        <samp class="fas fa-book" height="90" alt="Logo Bookiernes"></samp>

    <h2>Bookiernes</h2>
    </div>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">


      <p class="login-box-msg">Enviar sol·licitud per a poder tornar a entrar.</p>
      <form action="{% url 'BookiernesApp:reset_password' %}" method="post">
        {% csrf_token %}
       <div class="form-group">
                      <label >Nom d'usuari:</label>
 <input type="text" name="username" class="form-control" id="username" maxlength="140" required="">
                    </div>
                    <div class="form-group">
                      <label >Nom del correu electrònic:</label>
 <input type="email" name="email" class="form-control" id="email" maxlength="255" required="">
                    </div>
        <div class="form-group">
                      <label >Missatge curt:</label>
<textarea id="w3review" name="mesaje" rows="4" cols="43">
 Hola, he oblidat la contrasenya em pots ficar la contrasenya per defecte.
</textarea>
                    </div>
          <!-- /.col -->

            <button type="submit" class="btn btn-primary btn-block">Enviar</button>

          <!-- /.col -->
        </div>
      </form>



    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="../../static/BookiernesApp/js/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../static/BookiernesApp/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../static/BookiernesApp/js/adminlte.min.js"></script>

</body>
</html>

BookiernesApp/templates/html_templates/IT/It_UserList.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookiernes</title>
   <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">
    <!-- libreria para caja de texto  -->
{% endblock %}

 {% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">

        <ol class="breadcrumb float-sm-left">
              <li class="breadcrumb-item">Llistat de treballadors</li>
        </ol>


      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
<br>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Llistat de treballadors</h3>
                </div>
                <!-- /.card-header -->
              <div class="card-body">
                {% if messages %}

                {% for message in messages %}
                <br>
                <div class="container">
                <div class="row justify-content-md-center">
                <div class="col-md-6">
                  <div class="card card-success ">
                    <div class="card-header">
                      <h3 class="card-title">Èxit</h3>

                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
                        </button>
                      </div>
                      <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      {{message}}
                    </div>
                    <!-- /.card-body -->
                  </div>
                </div>
              </div>
            </div>
                {% endfor %}

                {% endif %}

                <div class="input-group input-group-sm" style="width: 250px;">

                    <input type="text" name="value_search" class="form-control float-right" placeholder="Buscar per nom d'usuari">



                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default" value="Submit">
                        <i class="fas fa-search"></i>
                      </button>
                    </div>
                  </div>

                </br>

                {% if page_obj.paginator.count >  0 %}
               <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Nom d'usuari</th>
                        <th>Rol </th>
                        <th>Usuaris actius</th>
                        <th>Opcions</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for obj_user in  page_obj %}
                    <tr>
                        <td>{{obj_user.username}}</td>
                        <td>{{obj_user.get_user_type_name}}</td>
                        <td>{{obj_user.get_activated}}</td>
                        <td><a href="{% url 'BookiernesApp:user_view' obj_user.id %}"><i class="nav-icon fas fa-eye"></i></a>
                            <a href="{% url 'BookiernesApp:user_edit_pass' obj_user.id %}"><i class="nav-icon fas fa-user-edit"></i></a>
                            {% if obj_user.is_active %}
                            <a href="{% url 'BookiernesApp:active_user' obj_user.id %}"><i class="nav-icon nav-success fas fa-user-plus text-green"></i></a>
                            {% else %}
                            <a href="{% url 'BookiernesApp:active_user' obj_user.id %}"><i class="nav-icon fas fa-user-times text-red"></i></a>
                            {% endif %}
                        </td>
                    </tr>



                    {% endfor %}
                    </tbody>
                </table>


                  <br>
                  <br>
            {% if is_paginated %}
              <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                  {% if page_obj.has_previous %}
                    <li class="page-item ">
                      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                    </li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                    <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endfor %}
                  {% if page_obj.has_next %}
                    <li class="page-item ">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                  {% else %}
                    <li class="page-item disabled">
                      <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                    </li>
                  {% endif %}
                </ul>
              </nav>
            {% endif %}

            {% else %}
              <br>  <br>
            <p class="text-center"> No hi ha cap treballador creat en aquest moment. </p>
            <br>  <br>
            {% endif %}

                </div>
              </div>



        </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}