BookiernesApp/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.views.generic import RedirectView, ListView

from django.conf import settings
from django.conf.urls.static import static

from BookiernesApp.views import *

app_name = "BookiernesApp"

urlpatterns = [
    path('', login_required(mainView), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),

    #Escritor
    # http://127.0.0.1:8000/writer_published/
    url(r'^writer_published/$', login_required(PublishedBooks.as_view()), name='writer_published_books'),
    # http://127.0.0.1:8000/writer_published/get_book/33
    url(r'^writer_published/get_book/(?P<pk>\d+)/$', login_required(Get_Books.as_view()), name='books'),
    # http://127.0.0.1:8000/writer_published/add_book/
    url(r'^writer_published/add_book/$', login_required(PublishBook.as_view()), name='writer_publish_book'),
    # http://127.0.0.1:8000/writer_published/edit_book/33
    url(r'^writer_published/edit_book/(?P<pk>\d+)/$', login_required(Edit_Book.as_view()), name='writer_modify_a_book'),
    # http://127.0.0.1:8000/writer_published/edit_book/33
    url(r'^writer_message/get_book/(?P<pk>\d+)/$', login_required(Chat_Book.as_view()), name='chat_book'),
    url(r'^writer_message/post_book/(?P<pk>\d+)/send/$', login_required(post_chat), name='send_message'),

    url(r'^writer_published/book_delete/(?P<pk>\d+)$', login_required(deleteBook), name='book_delete'),

    url(r'^writer_notification/(?P<pk>\d+)/$', login_required(writer_notification), name='notification'),

    url(r'^writer_published/serch/$', login_required(SerchBooks.as_view()), name='serch_book'),

    # Editor
    url(r'^editor_book_revision/$', login_required(EditorBookRevision.as_view()), name='editor_book_revision'),


    url(r'^editor_message/get_book/(?P<pk>\d+)/$', login_required(Editor_Chat_Book.as_view()), name='chat_book_editor'),
    url(r'^editor_message/post_book/(?P<pk>\d+)/send/$', login_required(editor_post_chat), name='send_message_editor'),
    url(r'^editor_notification/(?P<pk>\d+)/$', login_required(editor_notification), name='notification_editor'),


    # Main Editor
    #url(r'^maineditor_book_revision/$', login_required(MainEditorBookRevision.as_view()), name='maineditor_book_revision'),


    #url(r'^maineditor_message/get_book/(?P<pk>\d+)/$', login_required(Maineditor_Chat_Book.as_view()), name='chat_book_maineditor'),
    #url(r'^maineditor_message/post_book/(?P<pk>\d+)/send/$', login_required(maineditor_post_chat), name='send_message_maineditor'),
    #url(r'^maineditor_notification/(?P<pk>\d+)/$', login_required(maineditor_notification), name='notification_maineditor'),




    path('', SignUpView.as_view(), name='signup'),
    # writer

    # editor urls
    url(r'^editor_book_revision/$', EditorBookRevision.as_view(), name='editor_book_revision'),
    url(r'^editor_book_revision/book_revision_detail/(?P<pk>\d+)/$',
        EditorBookDetail.as_view(), name='editor_book_detail'),
    url(r'^editor_book_revision/book_revision_detail/(?P<pk>\d+)/accept_or_reject$',
        accept_or_reject, name='editor_accept_or_reject'),

    url(r'^editor_books_to_design/book_design_detail/(?P<pk>\d+)/$',
        EditorBookDesignDetail.as_view(), name='editor_design_detail'),

    path('editor_books_to_design', EditorBooksToDesign.as_view(), name='editor_books_to_design'),
    path('editor_image_petitions', EditorImagePetitions.as_view(), name='editor_image_petitions'),
    path('editor_image_petitions/image_petition_detail/<int:pk>/', EditorImagePetitionDetail.as_view(), name='image_petition_detail'),
    path('editor_image_petitions/new_petiton', EditorImagePetitionsCreate.as_view(), name='editor_image_petition_create'),

    # main editor urls
    # TODO create date_presented attribute to sort books
    url(r'^maineditor__books_presented_in_editorial/$',
        MainEditorBooksPresentedInEditorial.as_view(), name='maineditor_books_presented_editorial'),
    url(r'^maineditor__books_presented_in_editorial/book_presented_detail/(?P<pk>\d+)/$',
        MainEditorBookPresentedDetail.as_view(), name='maineditor_book_presented_detail'),
    url(r'^maineditor__books_presented_in_editorial/book_presented_detail/(?P<pk>\d+)/assign_or_reject$',
        assign_or_reject, name='maineditor_assign_or_reject'),


    # it urls
    url(r'^it_view/$', ItView.as_view(), name='user_list'),
    url(r'^it_view/get_user/(?P<pk>\d+)/$', ItDetailUser.as_view(), name='user_view'),
    url(r'^it_view/active_user/(?P<pk>\d+)/$', active_user, name='active_user'),
    url(r'^it_view/add_user/$', ITCrateUser.as_view(), name='create_user'),
    url(r'^it_view/edit_pass/(?P<pk>\d+)/$', ItPassword.as_view(), name='user_edit_pass'),
    url(r'^it_view/edit_pass_post/$', postEditPass, name='user_edit_pass_post'),
    url(r'^reset/password/$', ViewResetPass.as_view(), name='reset_password_view'),
    url(r'^post/reset/password/$', resetPass, name='reset_password'),


    # Graphic Designer main
    url(r'^main_graphic_designer/petitionview/$', AssignmentListImg.as_view(), name='main_petitionview_list'),
    url(r'^main_graphic_designer/get_petitionview/(?P<pk>\d+)/$', AssignmentDetaliImg.as_view(), name='main_petitionview_view'),

    url(r'^main_graphic_designer/bockmaquetat/$', AssignmentListBockMaquetat.as_view(), name='main_bockmaquetat_list'),
    url(r'^main_graphic_designer/get_bockmaquetat/(?P<pk>\d+)/$', AssignmentDetaliBockMaquetat.as_view(), name='main_bockmaquetat_view'),

    url(r'^main_graphic_designer/post_to_assign_GraphicDesigner/$', asignarGraphicDesigner,name='main_to_assign_graphicdesigner'),

    # Graphic Designer
    url(r'^graphic_designer/petitionview/$', ListImg.as_view(), name='petitionview_list'),
    url(r'^graphic_designer/get_petitionview/(?P<pk>\d+)/$', DetaliImg.as_view(), name='petitionview_view'),
    url(r'^graphic_designer/bockmaquetat/$', ListBockMaquetat.as_view(), name='bockmaquetat_list'),
    url(r'^graphic_designer/get_bockmaquetat/(?P<pk>\d+)/$', DetaliBockMaquetat.as_view(), name='bockmaquetat_view'),

    url(r'^graphic_designer/post_bockmaquetat/uploadbook/(?P<pk>\d+)/$', uploadbook, name='uploadbook_post'),
    url(r'^graphic_designer/post_bockmaquetat/uploadimg/$', uploadimg, name='uploadimg_post'),

    url(r'^graphic_designer/uploadimg/viewimg/(?P<pk>\d+)/$', GalleryImg.as_view(), name='get_uploadimg_view'),
    url(r'^graphic_designer/post_bockmaquetat/deleteimg/(?P<pk>\d+)/$', delete_img, name='get_deleteimg'),

    url(r'^graphic_designer_notification/(?P<pk>\d+)/$', designer_notification, name='notification_graphic_designer'),

    url(r'^graphic_designer_message/get_book/(?P<pk>\d+)/$', Graphic_designer_Chat_Book.as_view(), name='chat_book_graphic_designer'),
    url(r'^graphic_designer_message/post_book/(?P<pk>\d+)/send/$', graphic_designer_post_chat, name='send_message_graphic_designer'),




    #lector
    url(r'^landing_page/$', Landing_page_List.as_view(), name='landing_page'),
    url(r'^landing_page_search/(?P<type>\d+)/(?P<pk>\d+)/$', Landing_page_search.as_view(), name='landing_page_search'),
    url(r'^landing_page_search_from/$', Landing_page_search_from.as_view(), name='landing_page_search_from'),
    url(r'^autocomplete/book_autocomplete/$' , book_autocomplete , name='book_autocomplete'),

    url(r'^get_book/(?P<pk>\d+)/$', AssignmentDetaliImg.as_view(), name='get_book'),
    url(r'^register_readers/$', RegisterReaders.as_view(), name='register_readers'),
    url(r'^dowload_pdf/(?P<pk>\d+)/$', dowload_pdf, name='dowload_pdf'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookiernesSystem/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BookiernesApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookiernesApp/forms/book_forms.py
from django import forms
from django.core.exceptions import ValidationError

from BookiernesApp.models import *


class TranslatedBookForm(forms.Form):
    LANGUAGE_CHOICES = [
        ('en', 'English'),
        ('es', 'Spanish'),
    ]
    book_title = forms.CharField(label='Llibre a traduir', widget=forms.TextInput(attrs={'class': 'form-control'}))
    source_language = forms.CharField(label='Elegeix idioma del llibre \n',
                                      widget=forms.Select(attrs={
                                          'class': 'custom-select',
                                      }, choices=LANGUAGE_CHOICES))
    target_language = forms.CharField(label='Elegeix idioma al qual es vol traduir el llibre \n',
                                      widget=forms.Select(attrs={
                                          'class': 'custom-select',
                                      }, choices=LANGUAGE_CHOICES))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)  # Add request to the arguments so it can be used later
        super(TranslatedBookForm, self).__init__(*args, **kwargs)

    def clean(self):
        bookstqr = Book.objects.filter(
            Q(title=self.cleaned_data['book_title']) & Q(assigned_to__user=self.request.user) & (
                    Q(book_status="accepted") | Q(book_status="designing") | Q(book_status="published")))
        # Invalid input
        if not bookstqr:
            raise ValidationError(
                'Llibre invalid: %(book)s',
                code='invalid_book',
                params={'book': self.cleaned_data['book_title']},
            )
        elif bookstqr.count() > 1:
            raise ValidationError(
                'S´ha trobat dos llibres amb el mateix nom',
                code='invalid_book',
            )
        elif self.cleaned_data['source_language'] == self.cleaned_data['target_language']:
            raise ValidationError(
                'Idioma del llibre ha de ser diferent del idioma que es vol traduir',
                code='invalid_book',
            )
        # Title already done
        language = dict(self.LANGUAGE_CHOICES)[self.cleaned_data['target_language']]
        new_name = self.cleaned_data['book_title'] + " (" + language + ")"
        if Book.objects.filter(title=new_name):
            raise ValidationError(
                'Llibre %(book)s ja ha sigut traduït al %(language)s amb el nom de  " %(translated_book)s "',
                code='book_already_translated',
                params={'book': self.cleaned_data['book_title'], 'language': language, 'translated_book': new_name},
            )
        return self.cleaned_data


class SendImagePetition(forms.ModelForm):
    class Meta:
        model = ImagePetition
        fields = ['title', 'description']


class SendBookToDesign(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_to_design']


class Present_Book(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['author', 'title', 'theme', 'description', 'path', 'book_status']

        widgets = {
            'author': forms.TextInput(
                attrs={
                    'class': 'invisible',
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'titleCheck',
                }
            ),
            'theme': forms.Select(
                attrs={
                    'class': 'custom-select',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'name': 'content',
                    'id': 'editor',
                }
            ),
            'path': forms.FileInput(
                attrs={
                    'accept': '.md',

                }
            ),
            'book_status': forms.TextInput(
                attrs={
                    'class': 'invisible',
                }
            ),

        }


class Edit_Book(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['author', 'title', 'theme', 'description', 'path', 'book_status']

        widgets = {
            'author': forms.TextInput(
                attrs={
                    'class': 'invisible',
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'titleCheck',
                }
            ),
            'theme': forms.Select(
                attrs={
                    'class': 'custom-select',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'name': 'content',
                    'id': 'editor',
                }
            ),
            'path': forms.FileInput(
                attrs={
                    'accept': '.md',

                }
            ),
            'book_status': forms.TextInput(
                attrs={
                    'class': 'invisible',
                }
            ),

        }

BookiernesApp/views/maineditor_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic import TemplateView
from django.http import Http404
from django.shortcuts import render , redirect
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin

from datetime import datetime

from BookiernesApp.decorators import mainEditor_required, book_presented
from BookiernesApp.models import *

from BookiernesApp.decorators import mainEditor_required
from BookiernesApp.models import Book, User, Writer, Editor, Notification , Message

@method_decorator([login_required, mainEditor_required], name='dispatch')
class MainEditorBooksPresentedInEditorial(ListView):

    model = Book
    template_name = 'html_templates/MainEditor/MainEditor_PresentedBooks.html'
    #paginate_by = 100  # if pagination is desired


@method_decorator([login_required, mainEditor_required, book_presented], name='dispatch')
class MainEditorBookPresentedDetail(DetailView):

    model = Book
    template_name = 'html_templates/MainEditor/MainEditor_DetailPresentedBook.html'


@login_required
@mainEditor_required
def assign_or_reject(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.POST['action'] == 'assign':
        #Find editors with the same theme as the book
        possible_users = User.objects.all().filter(editor_profile__assigned_theme=book.theme)
        if not possible_users:
            return redirect('BookiernesApp:maineditor_books_presented_editorial')  #TODO test print error message, no users found with this theme
        #Find the least busy worker
        available_user = list(possible_users)[0]
        for user in possible_users:
            if available_user != user and user.editor_profile.get_availability() < available_user.editor_profile.get_availability():
                available_user = user
        #Modify book attributes
        book.assigned_to = available_user.editor_profile
        book.book_status = 'revised'
        book.main_editor_comment = request.POST['maineditor_approved_comment']
    elif request.POST['action'] == 'reject':
        book.book_status = 'rejected'
        book.main_editor_comment = request.POST['maineditor_rejected_comment']
    book.save()
    #Redirect
    return redirect('BookiernesApp:maineditor_books_presented_editorial')

BookiernesApp/views/shared_views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import CreateView

from BookiernesApp.forms import SignUpForm
from BookiernesApp.models import *


@login_required
def mainView(request):
    user = User.objects.get(username=request.user.username)
    if user.user_type == 'writer':
        return redirect('BookiernesApp:writer_published_books')
    elif user.user_type == 'editor':
        return redirect('BookiernesApp:editor_book_revision')
    elif user.user_type == 'main_editor':
        return redirect('BookiernesApp:maineditor_books_presented_editorial')
    elif user.user_type == 'it':
        return redirect('BookiernesApp:user_list')
    elif user.user_type == 'main_graphic_designer':
        return redirect('BookiernesApp:main_petitionview_list')
    elif user.user_type == 'graphic_designer':
        return redirect('BookiernesApp:petitionview_list')
    elif user.user_type == 'subscribed_reader':
        return redirect('BookiernesApp:landing_page')



class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'forms/form.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('BookiernesApp:home')

BookiernesApp/templates/html_templates/Editor/Chat.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookiernes</title>
   <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">
    <!-- libreria para caja de texto  -->
{% endblock %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
          
        <ol class="breadcrumb float-sm-left">
             <!-- <li class="breadcrumb-item"><a href="{% url 'BookiernesApp:writer_published_books' %}">Libros Presentados</a></li> -->
              <li class="breadcrumb-item active"> <a href="{% url 'BookiernesApp:books' book.id %}"> {{book.title}}</a> </li>
              <li class="breadcrumb-item active"> Missatges </li>
        </ol>
          
       
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
</br>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title"> Missatges </h3>
                </div>
                

                <!-- DIRECT CHAT -->
            <div class="card direct-chat direct-chat-primary">
                <div class="card-header">

                  <div class="card-tools">
                    <span title="{{messages_numbers}} New Messages" class="badge badge-primary">{{messages_numbers}}</span>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <!-- Conversations are loaded here -->
                  <div class="direct-chat-messages">
                    <!-- Message. Default to the left -->
                    {% for message in messages %}
                    {% if message.user_id == user.id  %}
                    <div class="direct-chat-msg">
                      <div class="direct-chat-infos clearfix">
                        <span class="direct-chat-name float-left">{{message.get_user_name}}</span>
                        <span class="direct-chat-timestamp float-right">{{message.date_received}}</span>
                      </div>
                      <!-- /.direct-chat-infos -->
                      <img class="direct-chat-img" src="{{message.user.get_img }}" alt="message user image">
                      <!-- /.direct-chat-img -->
                      <div class="direct-chat-text">
                        {{message.content }}
                      </div>
                      <!-- /.direct-chat-text -->
                    </div>
                    {% else %}
                              <!-- Message to the right -->
                              <div class="direct-chat-msg right">
                                <div class="direct-chat-infos clearfix">
                                  <span class="direct-chat-name float-right">{{message.get_user_name}}</span>
                                  <span class="direct-chat-timestamp float-left">{{message.date_received}}</span>
                                </div>
                                <!-- /.direct-chat-infos -->
                                <img class="direct-chat-img" src="{{message.user.get_img }}" alt="message user image">
                                <!-- /.direct-chat-img -->
                                <div class="direct-chat-text">
                                  {{message.content }}
                                </div>
                                <!-- /.direct-chat-text -->
                              </div>
                              <!-- /.direct-chat-msg -->
                    {% endif %}
                    <!-- /.direct-chat-msg -->
                    {% endfor %}
                   
  
                   
  
                   
  
                  </div>
                  <!--/.direct-chat-messages-->
  
                
                  <!-- /.direct-chat-pane -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <form action="{% url 'BookiernesApp:send_message_editor' book.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                      <input type="text" name="content" placeholder="Escriure un missatge" class="form-control">
                      <span class="input-group-append">
                        <button type="submit" class="btn btn-primary">Eviar</button>
                      </span>
                    </div>
                  </form>
                </div>
                <!-- /.card-footer-->
              </div>
              <!--/.direct-chat -->
            

               


              </div>

  
              
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

BookiernesApp/templates/html_templates/Editor/Editor_BooksToDesign.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookiernes</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">
    <!-- libreria para caja de texto  -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script> no ser que pasa   -->
{% endblock %}
{% block content %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- /.content-header -->
        <br>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                {% if messages %}
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">Èxit!</h4>
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Llibres a Maquetar</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right"
                                   placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                        <br>

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Títol</th>
                                <th>Autor</th>
                                <th>Tema</th>
                                <th>Opcions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for book in user.editor_profile.get_books_to_design %}
                                <tr>
                                    <td>{{ book.title }}</td>
                                    <td> {{ book.author }}</td>
                                    <td> {{ book.theme }}</td>
                                    <td><a href="{% url 'BookiernesApp:editor_design_detail' book.id %}"><i
                                            class="nav-icon fas fa-cogs"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
            <!-- /.content -->
        </section>
    </div>
{% endblock %}

BookiernesApp/templates/html_templates/Editor/Editor_ImagePetitions.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookiernes</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">
    <!-- libreria para caja de texto  -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script> no ser que pasa   -->
{% endblock %}
{% block content %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- /.content-header -->
        <br>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Llibres a revisar</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control float-right"
                                   placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>


                        </div>
                        <a href="{% url 'BookiernesApp:editor_image_petition_create' %}">
                            <button class="btn btn-success float-right" style="margin-bottom: 10px">
                                Crear petició d'imatge
                            </button>
                        </a>

                        <br>

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Títol</th>
                                <th>Opcions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for petition in user.editor_profile.editor_petition.all %}
                                <tr>
                                    <td>{{ petition.title }}</td>
                                    <td><a href="{% url 'BookiernesApp:image_petition_detail' petition.id %}"><i
                                            class="nav-icon fas fa-cogs"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
            <!-- /.content -->
        </section>
    </div>
{% endblock %}