BookiernesApp/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.views.generic import RedirectView, ListView

from django.conf import settings
from django.conf.urls.static import static

from BookiernesApp.views import *

app_name = "BookiernesApp"

urlpatterns = [
    path('', login_required(mainView), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),

    #Escritor
    # http://127.0.0.1:8000/writer_published/
    url(r'^writer_published/$', login_required(PublishedBooks.as_view()), name='writer_published_books'),
    # http://127.0.0.1:8000/writer_published/get_book/33
    url(r'^writer_published/get_book/(?P<pk>\d+)/$', login_required(Get_Books.as_view()), name='books'),
    # http://127.0.0.1:8000/writer_published/add_book/
    url(r'^writer_published/add_book/$', login_required(PublishBook.as_view()), name='writer_publish_book'),
    # http://127.0.0.1:8000/writer_published/edit_book/33
    url(r'^writer_published/edit_book/(?P<pk>\d+)/$', login_required(Edit_Book.as_view()), name='writer_modify_a_book'),
    # http://127.0.0.1:8000/writer_published/edit_book/33
    url(r'^writer_message/get_book/(?P<pk>\d+)/$', login_required(Chat_Book.as_view()), name='chat_book'),
    url(r'^writer_message/post_book/(?P<pk>\d+)/send/$', login_required(post_chat), name='send_message'),

    url(r'^writer_published/book_delete/(?P<pk>\d+)$', login_required(deleteBook), name='book_delete'),

    url(r'^writer_notification/(?P<pk>\d+)/$', login_required(writer_notification), name='notification'),

    url(r'^writer_published/serch/$', login_required(SerchBooks.as_view()), name='serch_book'),

    # Editor
    url(r'^editor_book_revision/$', login_required(EditorBookRevision.as_view()), name='editor_book_revision'),


    url(r'^editor_message/get_book/(?P<pk>\d+)/$', login_required(Editor_Chat_Book.as_view()), name='chat_book_editor'),
    url(r'^editor_message/post_book/(?P<pk>\d+)/send/$', login_required(editor_post_chat), name='send_message_editor'),
    url(r'^editor_notification/(?P<pk>\d+)/$', login_required(editor_notification), name='notification_editor'),


    # Main Editor
    #url(r'^maineditor_book_revision/$', login_required(MainEditorBookRevision.as_view()), name='maineditor_book_revision'),


    #url(r'^maineditor_message/get_book/(?P<pk>\d+)/$', login_required(Maineditor_Chat_Book.as_view()), name='chat_book_maineditor'),
    #url(r'^maineditor_message/post_book/(?P<pk>\d+)/send/$', login_required(maineditor_post_chat), name='send_message_maineditor'),
    #url(r'^maineditor_notification/(?P<pk>\d+)/$', login_required(maineditor_notification), name='notification_maineditor'),




    path('', SignUpView.as_view(), name='signup'),
    # writer

    # editor urls
    url(r'^editor_book_revision/$', EditorBookRevision.as_view(), name='editor_book_revision'),
    url(r'^editor_book_revision/book_revision_detail/(?P<pk>\d+)/$',
        EditorBookDetail.as_view(), name='editor_book_detail'),
    url(r'^editor_book_revision/book_revision_detail/(?P<pk>\d+)/accept_or_reject$',
        accept_or_reject, name='editor_accept_or_reject'),

    url(r'^editor_books_to_design/book_design_detail/(?P<pk>\d+)/$',
        EditorBookDesignDetail.as_view(), name='editor_design_detail'),

    path('editor_books_to_design', EditorBooksToDesign.as_view(), name='editor_books_to_design'),
    path('editor_image_petitions', EditorImagePetitions.as_view(), name='editor_image_petitions'),
    path('editor_image_petitions/image_petition_detail/<int:pk>/', EditorImagePetitionDetail.as_view(), name='image_petition_detail'),
    path('editor_image_petitions/new_petiton', EditorImagePetitionsCreate.as_view(), name='editor_image_petition_create'),

    # main editor urls
    # TODO create date_presented attribute to sort books
    url(r'^maineditor__books_presented_in_editorial/$',
        MainEditorBooksPresentedInEditorial.as_view(), name='maineditor_books_presented_editorial'),
    url(r'^maineditor__books_presented_in_editorial/book_presented_detail/(?P<pk>\d+)/$',
        MainEditorBookPresentedDetail.as_view(), name='maineditor_book_presented_detail'),
    url(r'^maineditor__books_presented_in_editorial/book_presented_detail/(?P<pk>\d+)/assign_or_reject$',
        assign_or_reject, name='maineditor_assign_or_reject'),


    # it urls
    url(r'^it_view/$', ItView.as_view(), name='user_list'),
    url(r'^it_view/get_user/(?P<pk>\d+)/$', ItDetailUser.as_view(), name='user_view'),
    url(r'^it_view/active_user/(?P<pk>\d+)/$', active_user, name='active_user'),
    url(r'^it_view/add_user/$', ITCrateUser.as_view(), name='create_user'),
    url(r'^it_view/edit_pass/(?P<pk>\d+)/$', ItPassword.as_view(), name='user_edit_pass'),
    url(r'^it_view/edit_pass_post/$', postEditPass, name='user_edit_pass_post'),
    url(r'^reset/password/$', ViewResetPass.as_view(), name='reset_password_view'),
    url(r'^post/reset/password/$', resetPass, name='reset_password'),


    # Graphic Designer main
    url(r'^main_graphic_designer/petitionview/$', AssignmentListImg.as_view(), name='main_petitionview_list'),
    url(r'^main_graphic_designer/get_petitionview/(?P<pk>\d+)/$', AssignmentDetaliImg.as_view(), name='main_petitionview_view'),

    url(r'^main_graphic_designer/bockmaquetat/$', AssignmentListBockMaquetat.as_view(), name='main_bockmaquetat_list'),
    url(r'^main_graphic_designer/get_bockmaquetat/(?P<pk>\d+)/$', AssignmentDetaliBockMaquetat.as_view(), name='main_bockmaquetat_view'),

    url(r'^main_graphic_designer/post_to_assign_GraphicDesigner/$', asignarGraphicDesigner,name='main_to_assign_graphicdesigner'),

    # Graphic Designer
    url(r'^graphic_designer/petitionview/$', ListImg.as_view(), name='petitionview_list'),
    url(r'^graphic_designer/get_petitionview/(?P<pk>\d+)/$', DetaliImg.as_view(), name='petitionview_view'),
    url(r'^graphic_designer/bockmaquetat/$', ListBockMaquetat.as_view(), name='bockmaquetat_list'),
    url(r'^graphic_designer/get_bockmaquetat/(?P<pk>\d+)/$', DetaliBockMaquetat.as_view(), name='bockmaquetat_view'),

    url(r'^graphic_designer/post_bockmaquetat/uploadbook/(?P<pk>\d+)/$', uploadbook, name='uploadbook_post'),
    url(r'^graphic_designer/post_bockmaquetat/uploadimg/$', uploadimg, name='uploadimg_post'),

    url(r'^graphic_designer/uploadimg/viewimg/(?P<pk>\d+)/$', GalleryImg.as_view(), name='get_uploadimg_view'),
    url(r'^graphic_designer/post_bockmaquetat/deleteimg/(?P<pk>\d+)/$', delete_img, name='get_deleteimg'),

    url(r'^graphic_designer_notification/(?P<pk>\d+)/$', designer_notification, name='notification_graphic_designer'),

    url(r'^graphic_designer_message/get_book/(?P<pk>\d+)/$', Graphic_designer_Chat_Book.as_view(), name='chat_book_graphic_designer'),
    url(r'^graphic_designer_message/post_book/(?P<pk>\d+)/send/$', graphic_designer_post_chat, name='send_message_graphic_designer'),




    #lector
    url(r'^landing_page/$', Landing_page_List.as_view(), name='landing_page'),
    url(r'^landing_page_search/(?P<type>\d+)/(?P<pk>\d+)/$', Landing_page_search.as_view(), name='landing_page_search'),
    url(r'^landing_page_search_from/$', Landing_page_search_from.as_view(), name='landing_page_search_from'),
    url(r'^autocomplete/book_autocomplete/$' , book_autocomplete , name='book_autocomplete'),

    url(r'^get_book/(?P<pk>\d+)/$', AssignmentDetaliImg.as_view(), name='get_book'),
    url(r'^register_readers/$', RegisterReaders.as_view(), name='register_readers'),
    url(r'^dowload_pdf/(?P<pk>\d+)/$', dowload_pdf, name='dowload_pdf'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookiernesSystem/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BookiernesApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookiernesApp/views/it_views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, TemplateView, CreateView, UpdateView, DeleteView, ListView
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib import messages
from django.contrib.messages import constants

from django.urls import  reverse_lazy
from django.http import Http404, HttpResponseRedirect
from django.conf import settings

from BookiernesApp.decorators import it_required
from BookiernesApp.forms import FormularioUsuario

from BookiernesApp.models import User, Theme


@method_decorator([login_required, it_required], name='dispatch')
class ItView(ListView):
    template_name = 'html_templates/IT/It_UserList.html'
    model = User
    paginate_by = 10

    def get_queryset(self):
        try:
            return User.objects.exclude(user_type = "subscribed_reader").exclude(username="admin")
        except:
            return 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj_user_count'] = User.objects.exclude(user_type="subscribed_reader").exclude(
            username="admin").count()
        return context


@method_decorator([login_required, it_required], name='dispatch')
class ItDetailUser(TemplateView):
    model = User
    template_name = 'html_templates/IT/It_DadesUser.html'


    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['obj_user_count'] = User.objects.exclude(user_type = "subscribed_reader").exclude(username="admin").count()
            context['obj_user'] = User.objects.get(id=self.kwargs['pk'])
            return context
        except:
            raise Http404("I can't access this page.")

@method_decorator([login_required, it_required], name='dispatch')
class ITCrateUser(SuccessMessageMixin, CreateView):
    model = User
    template_name = 'html_templates/IT/It_CreateUser.html'
    form_class = FormularioUsuario
    success_url = reverse_lazy('BookiernesApp:user_list')

    def get_success_message(self, cleaned_data):
        return "L'usuari %(name)s s'ha creat correctament. " % {'name': self.object.username}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj_user_count'] = User.objects.exclude(user_type="subscribed_reader").exclude(
            username="admin").count()
        context['Theme'] = Theme.objects.all()
        return context

@method_decorator([login_required, it_required], name='dispatch')
class ItPassword(TemplateView):
    template_name = 'html_templates/IT/ItEditPassword.html'

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['obj_user_count'] = User.objects.exclude(user_type="subscribed_reader").exclude(
                username="admin").count()
            context['obj_user'] = User.objects.get(id=self.kwargs['pk'])
            return context
        except:
            raise Http404("No puc accedir a aquesta pàgina.")


@login_required
@it_required
def postEditPass(request):
    if request.method == "POST":

        message = ""
        ok=0
        id = request.POST['pk']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        obj_user = User.objects.get(id=id)

        if pass1 != pass2 or (len(pass1)<8 and len(pass2)<8):
            message = "La contrasenya ha de tenir 8 caràcters i els dos camps han de ser iguals. "
        else:
            message = "A l'usuari %(nom)s se li ha canviat la contrasenya. " % {'nom': obj_user.username}
            ok = 1



        if ok == 1:
            messages.add_message(request, constants.SUCCESS, message)
            obj_user.set_password(pass2)
            obj_user.save()
            return redirect("BookiernesApp:user_list")
        else:
            messages.add_message(request, constants.ERROR, message)
            url = "/it_view/edit_pass/" + str(obj_user.id)
            return redirect(url)

    else:
        raise Http404("No puc accedir a aqueta pàgina.")


@method_decorator([login_required, it_required], name='dispatch')
class ViewResetPass(TemplateView):
    template_name = 'html_templates/IT/It_PeticonCabio.html'

@login_required
@it_required
def resetPass(request):
    return redirect("/")

@login_required
@it_required
def active_user(request, pk):
    try:
        obj_user=User.objects.get(id = pk)
        message= ""
        url="BookiernesApp:user_list"

        if obj_user.is_active == 1:
            obj_user.is_active=0
            message = "L'usuari %(nom)s s'ha desactivat correctament. " % {'nom': obj_user.username}
        else:
            obj_user.is_active = 1
            message = "L'usuari %(nom)s s'ha activat correctament. " % {'nom': obj_user.username}

        obj_user.save()


        messages.add_message(request, constants.SUCCESS, message)

        return redirect(url)

    except:
        raise Http404("No puc accedir a aquesta pàgina")

BookiernesApp/views/maineditor_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic import TemplateView
from django.http import Http404
from django.shortcuts import render , redirect
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin

from datetime import datetime

from BookiernesApp.decorators import mainEditor_required, book_presented
from BookiernesApp.models import *

from BookiernesApp.decorators import mainEditor_required
from BookiernesApp.models import Book, User, Writer, Editor, Notification , Message

@method_decorator([login_required, mainEditor_required], name='dispatch')
class MainEditorBooksPresentedInEditorial(ListView):

    model = Book
    template_name = 'html_templates/MainEditor/MainEditor_PresentedBooks.html'
    #paginate_by = 100  # if pagination is desired


@method_decorator([login_required, mainEditor_required, book_presented], name='dispatch')
class MainEditorBookPresentedDetail(DetailView):

    model = Book
    template_name = 'html_templates/MainEditor/MainEditor_DetailPresentedBook.html'


@login_required
@mainEditor_required
def assign_or_reject(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.POST['action'] == 'assign':
        #Find editors with the same theme as the book
        possible_users = User.objects.all().filter(editor_profile__assigned_theme=book.theme)
        if not possible_users:
            return redirect('BookiernesApp:maineditor_books_presented_editorial')  #TODO test print error message, no users found with this theme
        #Find the least busy worker
        available_user = list(possible_users)[0]
        for user in possible_users:
            if available_user != user and user.editor_profile.get_availability() < available_user.editor_profile.get_availability():
                available_user = user
        #Modify book attributes
        book.assigned_to = available_user.editor_profile
        book.book_status = 'revised'
        book.main_editor_comment = request.POST['maineditor_approved_comment']
    elif request.POST['action'] == 'reject':
        book.book_status = 'rejected'
        book.main_editor_comment = request.POST['maineditor_rejected_comment']
    book.save()
    #Redirect
    return redirect('BookiernesApp:maineditor_books_presented_editorial')

BookiernesApp/views/shared_views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import CreateView

from BookiernesApp.forms import SignUpForm
from BookiernesApp.models import *


@login_required
def mainView(request):
    user = User.objects.get(username=request.user.username)
    if user.user_type == 'writer':
        return redirect('BookiernesApp:writer_published_books')
    elif user.user_type == 'editor':
        return redirect('BookiernesApp:editor_book_revision')
    elif user.user_type == 'main_editor':
        return redirect('BookiernesApp:maineditor_books_presented_editorial')
    elif user.user_type == 'it':
        return redirect('BookiernesApp:user_list')
    elif user.user_type == 'main_graphic_designer':
        return redirect('BookiernesApp:main_petitionview_list')
    elif user.user_type == 'graphic_designer':
        return redirect('BookiernesApp:petitionview_list')
    elif user.user_type == 'subscribed_reader':
        return redirect('BookiernesApp:landing_page')



class SignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'forms/form.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('BookiernesApp:home')

BookiernesApp/templates/html_templates/Designer/Chat.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookiernes</title>
   <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">
    <!-- libreria para caja de texto  -->
{% endblock %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
          
        <ol class="breadcrumb float-sm-left">
              <li class="breadcrumb-item"><a href="{% url 'BookiernesApp:bockmaquetat_list' %}">Llibres per assigna'ls-hi una maquetació</a></li>
              <li class="breadcrumb-item active"><a href="{% url 'BookiernesApp:bockmaquetat_view' book.id %}"> Llibre maquetat {{book.title}}</a>  </li>
            <li class="breadcrumb-item active">  Missatges </li>
        </ol>
          
       
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
</br>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Missatges </h3>
                </div>
                

                <!-- DIRECT CHAT -->
            <div class="card direct-chat direct-chat-primary">
                <div class="card-header">

                  <div class="card-tools">
                    <span title="{{messages_numbers}} New Messages" class="badge badge-primary">{{messages_numbers}}</span>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <!-- Conversations are loaded here -->
                  <div class="direct-chat-messages">
                    <!-- Message. Default to the left -->
                    {% for message in messages %}
                    {% if message.user_id == user.id  %}
                    <div class="direct-chat-msg">
                      <div class="direct-chat-infos clearfix">
                        <span class="direct-chat-name float-left">{{message.get_user_name}}</span>
                        <span class="direct-chat-timestamp float-right">{{message.date_received}}</span>
                      </div>
                      <!-- /.direct-chat-infos -->
                      <img class="direct-chat-img" src="{{message.user.get_img }}" alt="message user image">
                      <!-- /.direct-chat-img -->
                      <div class="direct-chat-text">
                        {{message.content }}
                      </div>
                      <!-- /.direct-chat-text -->
                    </div>
                    {% else %}
                              <!-- Message to the right -->
                              <div class="direct-chat-msg right">
                                <div class="direct-chat-infos clearfix">
                                  <span class="direct-chat-name float-right">{{message.get_user_name}}</span>
                                  <span class="direct-chat-timestamp float-left">{{message.date_received}} </span>
                                </div>
                                <!-- /.direct-chat-infos -->
                                <img class="direct-chat-img" src="{{message.user.get_img }}" alt="message user image">
                                <!-- /.direct-chat-img -->
                                <div class="direct-chat-text">
                                  {{message.content }}
                                </div>
                                <!-- /.direct-chat-text -->
                              </div>
                              <!-- /.direct-chat-msg -->
                    {% endif %}
                    <!-- /.direct-chat-msg -->
                    {% endfor %}
                   
  
                   
  
                   
  
                  </div>
                  <!--/.direct-chat-messages-->
  
                
                  <!-- /.direct-chat-pane -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <form action="{% url 'BookiernesApp:send_message_graphic_designer' book.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                      <input type="text" name="content" placeholder="Escriure un missatge" class="form-control">
                      <span class="input-group-append">
                        <button type="submit" class="btn btn-primary">Eviar</button>
                      </span>
                    </div>
                  </form>
                </div>
                <!-- /.card-footer-->
              </div>
              <!--/.direct-chat -->
            

               


              </div>

  
              
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

BookiernesApp/templates/html_templates/Designer/Designer_DetailImg.html
{% extends "html_templates/Blocks/Base.html" %}
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bookiernes</title>
    <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/all.min.css">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Theme style -->
    <link rel="stylesheet" href="../../../static/BookiernesApp/css/adminlte.min.css">

<link rel="stylesheet" href="../../../static/BookiernesApp/js/dropzone-5.7.0/dist/dropzone.css">

    <!-- libreria para caja de texto  -->
{% endblock %}
{% block content %}

 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">

        <ol class="breadcrumb float-sm-left">

          <li class="breadcrumb-item"><a href="{% url 'BookiernesApp:petitionview_list' %}">Sol·licituds d'Imatges per assignar</a></li>
              <li class="breadcrumb-item active"> Sol·licitud {{imagepetition.title}} </li>
        </ol>


      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
<br>
<section class="content">


            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Sol·licitud {{imagepetition.title}}</h3>
              </div>

              <div class="row invoice-info p-3 mb-3">
                          <div class="col-sm-2 invoice-col">
                              <strong> Editor:</strong><br><br>
                              <strong> Títol:</strong><br><br>
                              <strong> Data:</strong><br><br>
                              <strong> Descripció:</strong><br><br>
                          </div>
                          <!-- /.col -->
                          <div class="col-sm-8 invoice-col">
                            {{imagepetition.editor.user.first_name}} {{imagepetition.editor.user.last_name}}<br><br>
                            {{imagepetition.title}}</br><br>
                              {{imagepetition.date_received}}</br><br>
                            {{imagepetition.description | safe }}</br><br>
                            </div>

              </div>
              <!-- /.card-body -->

                 <div class="d-flex justify-content-center">


                     <a href="{% url 'BookiernesApp:get_uploadimg_view' imagepetition.id %}">
                        <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                            <i class="fas fa-eye"></i> Imatges pujades
                        </button>
                    </a>

                       <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;"
                                data-toggle="modal" data-target="#modal-comet-dg">
                            <i class="fas fa-comment-dots"></i> Comentari del dissenyador gràfic principal
                        </button>
</div>

                  <div class="p-3 mb-3">
                     <form id="dropZoneForm" class="dropzone needsclick dz-clickable" action="#" method="post"
          enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{imagepetition.id}}">
             <div class="fallback">
            <input name="file" type="file" multiple/>
        </div>


    <button type="submit" id="submit-all"  class="btn btn-primary float-right" style="float: right">

         <i class="fas fa-upload"></i> Upload
                        </button>
        </form>
                  </div>
              </div>


            </div>
            <!-- /.card -->


<!-- The Modal -->
                    <div class="modal" id="modal-comet-dg">
                        <div class="modal-dialog modal-xl">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Comentari del dissenyador gràfic principal</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>


                                <div class="modal-body">
                                    {{ book.main_graphic_designer_comment | safe}}
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">

                                </div>

                            </div>
                        </div>
                    </div>



</section>
 </div>
   {% endblock %}


{% block script %}
<script src="../../../static/BookiernesApp/js/dropzone-5.7.0/dist/dropzone.js"></script>
<script>

 final_url = "http://127.0.0.1:8000/graphic_designer/post_bockmaquetat/uploadimg/";
    Dropzone.options.dropZoneForm = {
        url: final_url,
        addRemoveLinks: true,
        method: "POST",
        params: 'file_upload',
        dictFileTooBig: "El archivo es demasiado grande.",
        autoProcessQueue: false,
        acceptedFiles: '.png, .jpg, .jpeg',
        uploadMultiple: true,
        dictDefaultMessage: "Arrastra y suelta la imagen aquí para subirlos",
        clickable: true,
        headers: {
            'Access-Control-Request-Headers':'authorization,cache-control,x-requested-with',
            'Access-Control-Allow-Origin':'*'
            // remove Cache-Control and X-Requested-With
            // to be sent along with the request
        },
        init: function () {
            mydropzone = this;

            $("#submit-all").click(function (evt) {
                evt.preventDefault();
                evt.stopPropagation();
                var paymentNotes = $("#paymentNotes").val();
                mydropzone.autoProcessQueue = true;
                mydropzone.processQueue();

            });
            mydropzone.on('sending', function (file, xhr, formData) {

                var notes = $("#paymentNotes").val();
                var outgoingManualPaymentID = $("#outgoingManualPaymentID").val();
                console.log('notes from sending' + notes);
                console.log('notes from sending' + notes);
                formData.append('paymentNotes', notes);
                formData.append('outgoingManualPaymentID', outgoingManualPaymentID);
            });
        },
        success: function f(response) {
            console.log('response' + response);
            $('.dz-remove').hide();
        },
    };

</script>
{% endblock %}